import { BrewRecipe } from './types';

export const defaultRecipes: BrewRecipe[] = [
  {
    id: 'espresso-double',
    title: 'اسپرسو دبل شات حرفه‌ای',
    method: 'Espresso',
    coffeeWeight: 19,
    waterWeight: 38,
    grindSize: 'بسیار ریز (Fine)',
    temp: 93,
    steps: [
      { time: 0, description: 'شروع پمپ (Pre-infusion) - چک کردن فشار', waterAmount: 0 },
      { time: 5, description: 'ظهور اولین قطرات عصاره (First Drip)', waterAmount: 2 },
      { time: 15, description: 'جریان یکنواخت (دم موشی) و تغییر رنگ به عسلی', waterAmount: 20 },
      { time: 25, description: 'تغییر رنگ به زرد کمرنگ (Blonding) - آماده قطع کردن', waterAmount: 32 },
      { time: 30, description: 'قطع کامل عصاره‌گیری', waterAmount: 38 },
    ],
  },
  {
    id: 'v60-standard',
    title: 'V60 - تکنیک هاریو',
    method: 'V60',
    coffeeWeight: 20,
    waterWeight: 320,
    grindSize: 'متوسط رو به ریز (Medium-Fine)',
    temp: 93,
    steps: [
      { time: 0, description: 'بلومینگ: خیساندن تمام قهوه با ۶۰ گرم آب برای خروج گاز', waterAmount: 60 },
      { time: 45, description: 'ریزش اول: اضافه کردن آب تا ۲۰۰ گرم با حرکات چرخشی آرام', waterAmount: 200 },
      { time: 105, description: 'ریزش دوم: اضافه کردن باقی آب تا ۳۲۰ گرم (مرکز به بیرون)', waterAmount: 320 },
      { time: 180, description: 'پایان دم‌آوری: اجازه دهید آب کاملاً از بستر قهوه عبور کند', waterAmount: 320 },
    ],
  },
  {
    id: 'chemex-classic',
    title: 'کمکس کلاسیک (۳ کاپ)',
    method: 'Chemex',
    coffeeWeight: 30,
    waterWeight: 500,
    grindSize: 'متوسط رو به درشت (Medium-Coarse)',
    temp: 94,
    steps: [
      { time: 0, description: 'بلومینگ: ریختن ۶۰ گرم آب و هم زدن ملایم', waterAmount: 60 },
      { time: 45, description: 'ریزش مارپیچی: اضافه کردن آب تا ۳۰۰ گرم', waterAmount: 300 },
      { time: 105, description: 'ریزش نهایی: اضافه کردن آب تا ۵۰۰ گرم (از مرکز)', waterAmount: 500 },
      { time: 240, description: 'برداشتن فیلتر و سرو', waterAmount: 500 },
    ],
  },
  {
    id: 'aeropress-inverted',
    title: 'ائروپرس (روش معکوس)',
    method: 'Aeropress',
    coffeeWeight: 18,
    waterWeight: 200,
    grindSize: 'متوسط (Medium)',
    temp: 90,
    steps: [
      { time: 0, description: 'اضافه کردن ۱۰۰ گرم آب و ۵ بار هم زدن', waterAmount: 100 },
      { time: 30, description: 'اضافه کردن باقی آب تا ۲۰۰ گرم', waterAmount: 200 },
      { time: 60, description: 'بستن فیلتر و خارج کردن هوای اضافی', waterAmount: 200 },
      { time: 90, description: 'برگرداندن و پرس کردن با فشار یکنواخت (۳۰ ثانیه)', waterAmount: 200 },
    ],
  },
  {
    id: 'french-press-full',
    title: 'فرنچ پرس (فول بادی)',
    method: 'French Press',
    coffeeWeight: 30,
    waterWeight: 500,
    grindSize: 'درشت (Coarse)',
    temp: 95,
    steps: [
      { time: 0, description: 'ریختن تمام آب روی قهوه به صورت سریع', waterAmount: 500 },
      { time: 240, description: 'شکستن لایه رویی (Crust) و برداشتن کف روی قهوه', waterAmount: 500 },
      { time: 300, description: 'گذاشتن درب (بدون پرس) برای ته‌نشینی ذرات', waterAmount: 500 },
      { time: 480, description: 'پرس ملایم تا سطح قهوه و سرو', waterAmount: 500 },
    ],
  },
];
